# appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 900
      runas: ubuntu
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 120
      runas: ubuntu